version: '{branch}-{build}'

image: Visual Studio 2017

build:
  verbosity: minimal

environment:
  matrix:
  - BUILD: 'Release'
    CONFIG: installer
    SHADOW_BUILD_DIR: C:\projects\qgroundcontrol\build_windows_install
    QT_JOM_DIR: C:\Qt-QGC-5.12.6\Tools\QtCreator\bin
    QT_QMAKE_DIR: C:\Qt-QGC-5.12.6\5.12.6\msvc2017_64\bin
    EXTRA_LIB: extended

install:
  - git submodule update --init --recursive
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir %LOCALAPPDATA%\QtProject && copy test\qtlogging.ini %LOCALAPPDATA%\QtProject\
  - ps: |
      Write-Host "Installing ortools..." -ForegroundColor Cyan
      $zipPath = "$($env:USERPROFILE)\or-tools_VisualStudio2019-64bit_v8.0.8283.zip"
      Write-Host "Downloading..."
      (New-Object Net.WebClient).DownloadFile('https://github.com/google/or-tools/releases/download/v8.0/or-tools_VisualStudio2019-64bit_v8.0.8283.zip', $zipPath)
      Write-Host "Unzippind..."
      $dest = "$($env:APPVEYOR_BUILD_FOLDER)\$($env:EXTRA_LIB)"
      cmd /c start /wait 7z x $zipPath -oC:\or-tools
      cd C:\or-tools\or-tools_VisualStudio2019-64bit_v8.0.8283
      dir
      copy -r C:\or-tools\or-tools_VisualStudio2019-64bit_v8.0.8283 $dest
      Rename-Item -Path $dest\or-tools_VisualStudio2019-64bit_v8.0.8283 $dest\or-tools
      cd $dest
      dir
      Write-Host "Unzipped in $dest" -ForegroundColor Green

build_script:
  - mkdir %SHADOW_BUILD_DIR% && cd %SHADOW_BUILD_DIR% && %QT_QMAKE_DIR%\qmake -r CONFIG+=%CONFIG% %APPVEYOR_BUILD_FOLDER%\tets.pro
  - cd %SHADOW_BUILD_DIR% && %QT_JOM_DIR%\jom
# Generate the source server information to embed in the PDB
# Temporarily disabled while we try to figure out where this is located on appveyor image
#  - '"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\srcsrv\srctool.exe" -r -u "%SHADOW_BUILD_DIR%\qgc-app\qgroundcontrol.pdb" | grep qgroundcontrol | grep -v moc_ | grep -v libs\\mavlink | grep -v build_windows_install | python %APPVEYOR_BUILD_FOLDER%\deploy\genPDBsrcsrv.py > %SHADOW_BUILD_DIR%\qgc-app\qgroundcontrol.pdb.srcsrv'
# write the source server info
#  - '"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\srcsrv\pdbstr.exe" -w -i:%SHADOW_BUILD_DIR%\qgc-app\qgroundcontrol.pdb.srcsrv -p:%SHADOW_BUILD_DIR%\qgc-app\qgroundcontrol.pdb -s:srcsrv'
# build the symbol / PE store
#  - 'cd %APPVEYOR_BUILD_FOLDER% && "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\symstore.exe" add /compress /s symbols /f %SHADOW_BUILD_DIR%\qgc-app\qgroundcontrol.pdb /t qgroundcontrol'
#  - 'cd %APPVEYOR_BUILD_FOLDER% && "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\symstore.exe" add /compress /s symbols /f %SHADOW_BUILD_DIR%\qgc-app\qgroundcontrol.exe /t qgroundcontrol'
#  - ps: 'cd $env:appveyor_build_folder; .\deploy\lowercaseify_symbolstore.ps1'

artifacts:
  - path: QGroundControl-installer.exe
    name: qgcinstaller
  - path: build_windows_install\staging\qgroundcontrol.pdb
    name: pdb

